---
title: "WFA48000 Research Credits"
output: 
  html_document:
    includes:
      after_body: _includes/include_footer.html
      in_header: _includes/header_banner.html 
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

<!--
library(knitr)
rmarkdown::render_site("resources.Rmd")# build website
rmarkdown::render_site()# build website
-->


# Useful Resources 

Below are links for varying resources that may be useful to 
your professional development. If you find content that you believe
will be useful to the group and future readers, please 
post a comment below. 

## Communications

### Written

1. [How to write a scientific paper](PDF/write-01.pdf)
1. [How to write and defend your thesis](https://students.fisheries.org/writing-resources/how-to-write-and-defend-your-thesis/)
1. [Writing a Literature Review: Six Steps to Get You from Start to Finish](PDF/write-02.pdf) ^[http://getalifephd.blogspot.com/2016/02/writing-literature-review-six-steps-to.html]
1. [The 5 pivotal paragraphs in a paper](PDF/write-03.pdf)  ^[https://dynamicecology.wordpress.com/2016/02/24/the-5-pivotal-paragraphs-in-a-paper/]
1. [Writing Manuscripts: The Alternative 'Guide to Authors'](PDF/write-04.pdf) ^[https://methodsblog.wordpress.com/2016/03/15/writing-manuscripts/]
1. [Top tips for starting a new research topic: systematic quantitative literature reviews](PDF/write-07.pdf) ^[https://www.iccs.org.uk/top-tips-for-starting-a-new-research-topic-systematic-quantitative-literature-reviews/]
1. [Ten Simple Rules for Writing a Literature Review](PDF/write-06.pdf) ^[http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003149]
2. [Three Writing Tips From Pulitzer Prize-Winning Author Jennifer Egan](PDF/write-08.pdf) ^[http://lifehacker.com/three-writing-tips-from-pulitzer-prize-winning-author-j-1786507353/amp]
1. [From an Engineer to an Author, I Find These Writing Tips Really Helpful ](PDF/write-09.pdf)^[http://www.lifehack.org/622355/x-hacks-to-largely-improve-your-writing]
1. [Advice on writing research articles](PDF/write-10.pdf)^[http://andrewgelman.com/2009/07/advice_on_writi/]
1. [How to Write a Publishable Paper as a Class Project](PDF/write-11.pdf)^[https://gking.harvard.edu/papers]
1. [Advice on Research and Writing: A collection of advice about how to do research and how to communicate effectively (primarily for computer scientists).](http://www.cs.cmu.edu/afs/cs.cmu.edu/user/mleone/web/how-to.html)
1. [Rough drafts, getting words on the page, and the pain – and pleasure – of writing](https://dynamicecology.wordpress.com/2018/06/04/rough-drafts-getting-words-on-the-page-and-the-pain-and-pleasure-of-writing/amp/)

### Oral

1. [Making conference talks compelling and meaningful](PDF/oral-01.pdf) ^[http://evol-eco.blogspot.com/2017/07/making-conference-talks-compelling-and.html]
1. [How Google's CEO Creates Brain-Friendly Presentations](PDF/oral-02.pdf) ^[http://google.com/newsstand/s/CBIwwYSZ0Tk]
1. [How to give a good research talk](PDF/oral-03.pdf)^[https://www.microsoft.com/en-us/research/academic-program/give-great-research-talk/]

### Web

1. [Find the Best Color Scheme for Your Website with This Guide](PDF/web-01.pdf) ^[http://lifehacker.com/find-the-best-color-scheme-for-your-website-with-this-g-1769424137]

### Media

1. [A Video is Worth a Million Words: Why You Should Make a Video about YOUR Article](PDF/media-01.pdf) ^[https://methodsblog.wordpress.com/2016/04/28/videos-about-articles/]

### Model
1. [Cartwright, S. J., K. M. Bowgen, C. Collop, K. Hyder, J. Nabe-Nielsen, R. Stafford, R. A. Stillman, R. B. Thorpe, and R. M. Sibly. 2016. Review: Communicating complex ecological models to non-scientist end users. Ecological Modelling 338:51-59.](PDF/C269.pdf))

## Networking and meetings

1.  [Summer conference season advice](PDF/network-01.pdf)^[https://dynamicecology.wordpress.com/2017/05/03/summer-conference-season-advice/#more-42767]
1.  [Maximize Your Meeting: A Student's Guide to AFS Meetings](PDF/network-02.pdf)^[http://www.tandfonline.com/loi/ufsh20]
1.  [Seven top tips for making the most of huge conferences](PDF/network-03.pdf)
1. [13 Mistakes Not to Make When Attending a Conference](PDF/network-01.pdf)^[https://www.forbes.com/sites/emmajohnson/2014/09/22/13-mistakes-not-to-make-when-attending-a-conference/print/]

## Goals and objectives

1. [Here's a simple trick to achieve your long-term 
goals](pdf/long-term-goals.pdf) ^[http://alifeofproductivity.com/a-simple-trick-to-achieve-long-term-goals]


## Field Sampling 

* [Better Safe than Sorry: Planning for Safe and Successful Fieldwork](PDF/field-01.pdf)
<!--
LOGISTICS OF ECOLOGICAL SAMPLING ON LARGE RIVERS https://cfpub.epa.gov/si/si_public_record_report.cfm?dirEntryId=63181
-->